Resources:
  myEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-467ca739
      Tags:
        - Key: "Name"
          Value: !Join 
            - ""
            - - "EC2 Instance for"
              - !Ref AWS::Region
      SecurityGroups:
      - !Ref mtySecrityGrouops
  mySecurityGroups:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'       

